name: Go Echo app CI
run-name: Go Echo app CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  print_tag_name:
    runs-on: ubuntu-latest
    steps:
      - name: Print tag name
        run: |
          echo "Hello World!"
          echo ${{ github.ref_name }}
  