name: Go Echo app CI
run-name: Go Echo app CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  test-app:
    runs-on: ubuntu-latest
    container: golang:alpine
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Install dependencies
        run: go get .
      - name: Test the app
        run: go test